### ISSUE TITLE
Support for Tabulator CSV Download

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#122]
I just saw on the guide that data download isn't supported yet, so thought I might open this request here. Cheers!

**Comment by rjaros** [comment]
I'v added `downloadCSV`, `downloadJSON` and `downloadHTML` methods to the `Tabulator` component. Those three formats are built-in and don't require additional libraries. Unfortunately PDF and XLSX formats do require external JS libraries, so no direct support for them at the moment. But because we have access to the `JsTabulator` native object, we can always try to use download API methods directly, for all formats.
