### ISSUE TITLE
Browserify & KVision

### ISSUE THREAD

**Issue by joerg-rade** [rjaros/kvision#134]
From https://stackoverflow.com/questions/35071937/use-npm-package-on-client-side I've learned that theroretically it's possible to use npm libs on the client by means of [browserify](http://browserify.org/).

Would this be possible with KVision as well?
If it is already possible, is there an example?

**Comment by rjaros** [comment]
As far as I understand Browserify just gives you a way to use `require` in the browser. But KVision uses webpack, so it's not really necessary, because webpack lets you do the same.

You can use a npm library with KVision, as long as it can work in the browser. Some libraries are designed for browser and some are designed or Node.js only. You need to check the documentation of the module you are interested in.

If you need an example - `Pokedex` app uses `hammerjs` npm library for touch gestures.

**Comment by joerg-rade** [comment]
Thanks for explanation and pointer!
