### ISSUE TITLE
Center of DockPanel is replaced by last add call

### ISSUE THREAD

**Issue by SKeeneCode** [rjaros/kvision#153]
New to KVision, trying to use the dockPanel:

```
class HomeTab : DockPanel() {
    init {
        add(h1("TOP"), Side.UP)
        add(h1("LEFT"), Side.LEFT)
        add(h1("RIGHT"), Side.RIGHT)
        add(h1("DOWN"), Side.DOWN)
        add(h1("CENTER"), Side.CENTER)
    }
}
```
Results in expected behaviour:
![image](https://user-images.githubusercontent.com/32420836/82237325-5cef8300-992d-11ea-84b3-349f86220226.png)

But if I swap the add calls around:

```
class HomeTab : DockPanel() {
    init {
        add(h1("TOP"), Side.UP)
        add(h1("LEFT"), Side.LEFT)
        add(h1("RIGHT"), Side.RIGHT)
        add(h1("CENTER"), Side.CENTER)
        add(h1("DOWN"), Side.DOWN)
    }
}
```

Results in "Center" being replaced by "Down". Center will always be replaced by whatever the last add call is.

I run into similar issues when trying to use `centerComponent =` to set components...

![image](https://user-images.githubusercontent.com/32420836/82237428-86a8aa00-992d-11ea-8d87-56b12ac29be6.png)

**Comment by rjaros** [comment]
All `add` methods take a `Component` object as a parameter. You should pass an object to them. But you are using DSL builder function `h1` instead of the constructor `H1` (the difference is the lower/upper case of the first letter). DSL builder function creates and returns an object as well, but it also adds it to the parent container using default `add` method (with one parameter). So in your example you are adding all these `H1` components to the parent container twice. And the default `add` method for `DockPanel` is mapped to `add(child, Side.CENTER)` call. That's why your last call always adds the component as center.

**Comment by SKeeneCode** [comment]
Perfect, thanks for the explanation I understand a lot more now ^.^
