### ISSUE TITLE
Headers for RestClient

### ISSUE THREAD

**Issue by marcelorcorrea** [rjaros/kvision#193]
Hi there!
Very useful lib, congratz!

I have a question regarding the `RestClient` object. 
Is there a way to set headers in the object for requesting a RestApi?

Another question:
How can I wait for the response of a form submission request?
Or is there a way to set the values of a form to a `onClick` event of a button?

Thanks!

**Comment by rjaros** [comment]
Hello and thanks for your feedback!

You can set request headers (and do other things as well) using `beforeSend : ((JQueryXHR, JQueryAjaxSettings) -> Boolean)` function parameter. Look how authorization is implementend in the RealWorld example app:
https://github.com/rjaros/kvision-realworld-example-app/blob/master/src/main/kotlin/io/realworld/Api.kt#L16-L55

As for the second question I'm not sure what is your use case. Generally classical form submission should not be used in single page applications (because form submission reloads the whole page). Instead you should process the form data with your code on the client side and send the data to the server using some kind of API calls. 

KVision allows you to easily bind a data class with a `FormPanel`. It's described in the guide here: 
https://kvision.gitbook.io/kvision-guide/part-2-advanced-features/forms#data-binding. 

But you can also use plain HTML form and just intercept `onsubmit` event to get the data and call some rest api. Once again I'll just give a sample from the RealWorld example:
https://github.com/rjaros/kvision-realworld-example-app/blob/master/src/main/kotlin/io/realworld/layout/users/Register.kt#L64

As JavaScript environment is asynchronous you can't just "wait" for the response. But you can use Kotlin coroutines to make your code look nice.

**Comment by marcelorcorrea** [comment]
Hi Robert!
Thanks for replying so fast and for the explanations!!
I got everything working thanks to your answer!
Pretty handy lib. Congratz once again!
