### ISSUE TITLE
Ktor with an observable on client side

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#22]
I'm trying to figure out if its feasible to use an observable on the server side drive a subscriber on the client side.
Let's say I have an observable array on the Ktor server and a service of something like getArray which updates a list on the client side. Is there any way to have the array on the server drive a change on the client without calling getArray again?

**Comment by rjaros** [comment]
You probably need websockets for that, but at the moment there is no support for websockets in KVision.

**Comment by robert-cronin** [comment]
I guess I could turn this into a feature request if it fits into the KVision plan, otherwise KTor has a websocket functionality that I can use to trigger updates: https://ktor.io/servers/features/websockets.html

**Comment by rjaros** [comment]
Support for websockets connections is added in KVision 0.0.32. It allows to use Kotlin coroutines channels to send typed objects in both directions between the client and the Ktor server. The guide is not yet updated so you can look at the [tweets-fullstack-ktor](https://github.com/rjaros/kvision-examples/tree/master/tweets-fullstack-ktor) example - it has been rewritten to use websockets instead of standard rest endpoints.
At the moment websockets support is available for Ktor module only.

**Comment by rjaros** [comment]
I've updated the documentation.
