### ISSUE TITLE
Clearer Setup Documentation

### ISSUE THREAD

**Issue by sfbaker7** [rjaros/kvision#276]
Hi, new to Kvision and FE development (java, BE, Ant background). I had some feedback/requests regarding the "[setting up](https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/setting-up)" portion of the documentation. 

I find that the build.gradle.kts file introduces a ton of dependencies and configurations without the explanation of what each one does. As a newcomer, I'm super hesitant of throwing the kitchen sink into a new application with settings I don't know. Furthermore, as a webpack newbie, it would be helpful to know how the runtask target relates to the webpack task, and how I might be able to extend, reduce, and customize these configurations to suit my needs. 

A few ideas that might help make it cleaner:

* an approach similar to [Ktor's](https://ktor.io/docs/creating-http-apis.html#dependencies) would be helpful for explaining dependencies
* the bare minimum dependencies for getting hello world running 
* more detail on the webpack portion / runtask section and how to organize it for your needs
* A setup from scratch instead of having to clone a template repo

**Comment by rjaros** [comment]
Hi,
Thank you for your feedback :-)

The "setting up" page could actually be improved, because the standard "template" project build configuration is a bit complex. But in fact most of this setup is created for gettext translations support. If you don't need or use translations you can remove almost everything and start from scratch. 

I suggest looking at the "mini-template" project - https://github.com/rjaros/kvision-examples/blob/master/mini-template/build.gradle.kts. It's build configuration is standard and very simple. And that's really all you need to start with KVision. You can add other features later, when you need them.

**Comment by rjaros** [comment]
I'll probably make changes to the guide with the 5.0 release.

**Comment by sfbaker7** [comment]
great - that's useful context! thanks for the quick response and pointer to the mini-template, that's exactly what I was looking for. Looking forward to 5.0

**Comment by rjaros** [comment]
I've moved most of non-standard project configuration to the KVision Gradle plugin. Build files for all example projects are now a lot smaller and cleaner.
