### ISSUE TITLE
ResponsiveGridPanel support multiple GridSize

### ISSUE THREAD

**Issue by iamcyw** [rjaros/kvision#287]
Hi @rjaros , 
Can ResponsiveGridPanel support multiple GridSize?
Many times, we need to set col-* and col-lg-* at the same time to optimize the experience of different resolutions

**Comment by rjaros** [comment]
Hi!

Could you please provide an example of what you would like to achieve?

**Comment by iamcyw** [comment]
![Xnip2021-07-30_11-08-24](https://user-images.githubusercontent.com/11208441/127593964-b68c80bd-eeb8-46a7-bf38-4ad21ad011d2.jpg)

![image](https://user-images.githubusercontent.com/11208441/127594113-5f548de3-3d79-4349-8218-3545772dbfe8.png)

like this,If I only use col-lg-3 in large resolution, it will become 4 lines in small screen. so, it is need to set a group of large resolution and small resolution at the same time

**Comment by rjaros** [comment]
`ResponsiveGridPanel` is just a simple helper class, which takes children attributes (row, col, size and offset) and calculates bootstrap classes from them. It can't automatically support more sizes, because you would have to provide different attributes for different sizes. It would make the component API very complex and in my opinion it doesn't make sense. If you know your needs, just use bootstrap classes directly, creating the correct markup with KVision DSL (using `div`'s).

But if you need just some small adjustments to the `ResponsiveGridPanel`, I've added additional `className` parameter to `add()` and `options()` functions. It will be available with KVision 5 release.

**Comment by iamcyw** [comment]
Well, this is a way to solve,  thanks 👏
