### ISSUE TITLE
Modal Alert issue

### ISSUE THREAD

**Issue by jjdestef3** [rjaros/kvision#29]
Hi,

Using KVision 0.0.31. When I attempt to show a modal Alert I get a javascript error stating that tmp$.modal is not a function. If I add a custom bootstrap theme and put an href in the index.html for it (css/bootstrap.min.css) then the error goes away. Seems that it might be an issue loading the bootstrap.js?

Quick example of this issue:

root = Root("fhirApp") {
            navbar(label = "My Meds", type = NavbarType.FIXEDTOP, inverted = true)

            GlobalScope.launch {
                try {
                    val result = PatientService.patientInContext()
                    add(PatientHeader(result))
                    throw Exception()
                } catch (e: Exception) {
                    console.log(e)
                    Alert.show("Alert dialog", "Lorem ipsum dolor sit amet, consectetur adipiscing.")
                } finally {
                    val div = document.getElementById("loaderDiv")
                    div?.remove()
                }
            }

            add(LoaderPanel("loaderDiv"))
        }
   
Thanks

**Comment by rjaros** [comment]
Hi,
Your code is working fine for me. The only way I can reproduce your problem is by removing kvision-bootstrap module dependency. Do you try to use KVision without bootstrap module, as described here: https://kvision.gitbook.io/kvision-guide/part-1-fundamentals/themes#using-kvision-without-bootstrap? If so, you just can't use modals (and other bootstrap components) without this module. If I'm wrong, and you have kvision-bootstrap module, maybe you can share some more code and I'll try to help.

**Comment by jjdestef3** [comment]
Hi,

Sorry for the late reply. Misconfiguration on my part.


Thanks
