### ISSUE TITLE
override fun afterInsert no longer working

### ISSUE THREAD

**Issue by drammelt** [rjaros/kvision#330]
Since upgrading to kvision 5.7.1 from 5.6.1 I have noticed the afterInsert override functions no longer work.

```
    override fun afterInsert(node: VNode) {
        super.afterInsert(node)
        console.log("After insert fun")
    }
```
Prints nothing

However hooks appear to work fine.
```
textInput {
                    id = GOOGLE_MAP_FIELD_ID
                }.addAfterInsertHook { vNode ->
                    console.log("After insert hook")
                }
```

Works fine.

**Comment by rjaros** [comment]
Hi
Unfortunately I can't reproduce your problem. Overriding `afterInsert` is used internally by lots of KVision components, so it definitely work. You can check this simple test application:
```
class MyPanel : SimplePanel(className = "my-panel") {
    override fun afterInsert(node: VNode) {
        super.afterInsert(node)
        println("afterInsert called")
    }
}

class App : Application() {

    override fun start() {
        root("kvapp") {
            add(MyPanel())
        }
    }
}

fun main() {
    startApplication(::App, module.hot, BootstrapModule, BootstrapCssModule, CoreModule)
}

```  
Could you please give some more information about your use case? 

Also note, there were some major optimizations introduced in KVision 5.5.0, and DOM nodes are now re-used whenever possible. So `afterInsert` is called less frequently than before. If your component needs to have it's own DOM node instance (e.g. because it's using some external JS library) you can call `useSnabbdomDistinctKey()` method in the `init {}` block, like this:
```
class MyPanel : SimplePanel(className = "my-panel") {
    init {
        useSnabbdomDistinctKey()
    }

    override fun afterInsert(node: VNode) {
        super.afterInsert(node)
        // node.elm DOM node is not shared between components 
        println("afterInsert called")
    }
}
```

**Comment by drammelt** [comment]
Thank you
