### ISSUE TITLE
How to export tabulator data to Excel

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#340]
How can I implement exporting of tabulator data to excel file and enable the user to save it on his local machine folder?

**Comment by rjaros** [comment]
There is no direct support for Excel format in KVision, because an additional library is needed. But it's very easy to use by:
1. Adding a SheetJS library to your `index.html`:
`<script type="text/javascript" src="https://oss.sheetjs.com/sheetjs/xlsx.full.min.js"></script>`
2. Starting export with:
`table.jsTabulator?.download("xlsx", "data.xlsx", obj<Tabulator.DownloadOptions> {sheetName = "MyData"}, "all")`

**Comment by chavu** [comment]
I am getting unrolved reference error on 'DownloadOptions':
```
obj<Tabulator.DownloadOptions> {sheetName = "IssueLog"}
```

**Comment by rjaros** [comment]
Make sure you are importing `import io.kvision.tabulator.js.Tabulator.DownloadOptions` (from the `js` subpackage)

**Comment by chavu** [comment]
Thanks that worked. I'm noticing it's exporting only fields(columns) on display in the table. How can I include additional fields which are part of the data model but not included on the columns?

**Comment by rjaros** [comment]
I'm not sure, but you can try adding hidden columns with your data (by using `visible = false` and `download = true` properties). See: http://tabulator.info/docs/5.0/download#advanced-show
