### ISSUE TITLE
How to filter by date filed in tabulator table?

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#349]
I would like to provode a user with multiple filter input components including date field. My code below works well without the date field but when I include the date field it failes for all. 

````
            console.log(myForm.dateRaisedElement.value)
            setFilter { logIssue->
                myForm.testerElement.value.let { it == logIssue.testerId.toString() || it == null } &&
         //               myForm.dateRaisedElement.value!!.toStringF("YYYY-MM-DD")?.let { it == logIssue.dateRaised!!.toStringF("YYYY-MM-DD") || it == null } &&

                        myForm.functionalAreaElement.value.let { it == logIssue.functionalAreaId.toString() || it == null } &&
            }?: true

            myForm.applyButton.onClick {
                issueLogTable.applyFilter()
            }

```

**Comment by rjaros** [comment]
Hi,
I suppose you have a logical error in this code because you are using  `!!`  and `?.let { }` in the commented line. So when `myForm.dateRaisedElement.value` is `null` you will get the exception. This line should probably look more like this to be consistent with the others conditions:
```
myForm.dateRaisedElement.value?.toStringF("YYYY-MM-DD").let { it == logIssue.dateRaised!!.toStringF("YYYY-MM-DD") || it == null } &&
```
If it sill fails you will need to provide more information. What error do you see? Do you use tabulator with `@Serializable` data model by passing `serializer` parameter? Please also log to the console and check what is the value of `logIssue.dateRaised` property. Perhaps it's not a `Date` object.

**Comment by chavu** [comment]
This worked. Thank you very much.
