### ISSUE TITLE
Hot Replacement 35 sec delay with showcase example

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#363]
I'm trying showcase example and delay between I save code modification in IntelliJ and reflecting it in browser is 
about 35 seconds. 
How can I run it in such a way that changes would be getting picked up in more reasonable time?

Thanks

**Comment by rjaros** [comment]
Use the legacy compiler. KVision still fully supports the old compiler and I use it myself for development because it's really fast. On my computer the delay with IR is 26 seconds vs. 4 seconds with legacy.

You can use the legacy compiler by changing `kotlin.js.compiler=legacy` in your `gradle.properties`.

**Comment by mgrouch** [comment]
Thanks. That did make a lot of difference
