### ISSUE TITLE
Dynamic SVG

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#368]
I'd like to write a library on top of kvision to display scalable SVG gauges (let's say compass, wind direction)

I want to write SVG into DOM tree (as inline svg). SVG need to be styled via CSS.

The arrows positions need to be displayed based on data binding to a value.

The value would come from TCP or UDP socket that needs to be opened directly from a browser.

What are my options? How is better to approach it? I'm just starting using Kotlin and KVision. I have long experience with Java.

Thanks

**Comment by rjaros** [comment]
When it comes to creating and rendering SVG in KVision, please check this issues: https://github.com/rjaros/kvision/issues/117 and https://github.com/rjaros/kvision/issues/243. You can find some information on the topic in my comments.

Opening a socket connection directly from the browser is generally not possible because of security risk (see: https://stackoverflow.com/a/8053026). There are some workarounds that require a proxy or other technology to be used, but I would not advise this direction. Instead you should use well known browser technologies - REST API, plain HTTP and/or WebSockets. KVision allows you to easily work with these.

**Comment by mgrouch** [comment]
Thanks
