### ISSUE TITLE
Example for styling needed

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#400]
An additional example where CSS is getting compiled by gradle on the fly from bootstrap and tabulator SASS would be very useful.
Currently styling with KVision is very time consuming.

Thanks

**Comment by rjaros** [comment]
You can't use different styles for tabulator component at the moment, because the css is always included by the module. Css module could be separated in the future, but not before KVision 6.0 (it would be a breaking change).
As for styling with SASS instead of the default Bootstrap css you should have a look at [KVision website sources](https://github.com/rjaros/kvision-io) - it's using Bulma SASS customized sources. Using Bootstrap SASS would be analogous.

**Comment by rjaros** [comment]
Styling tabulator is now possible
