### ISSUE TITLE
Extending Leaflet map's options

### ISSUE THREAD

**Issue by joaofig** [rjaros/kvision#404]
I am currently using the [Leaflet.contextmenu](https://github.com/aratcliffe/Leaflet.contextmenu) extension to implement context menus on Leaflet maps. From my understanding of the code's inner workings, I must extend some interfaces, such as `PolylineOptions` and `LeafletMapOptions`. I hit a roadblock when trying to pass the extended `LeafletMapOptions` to the map creation code. Unfortunately, this extension only works correctly when the map has one root context menu, so I must create it. My lack of advanced experience with Kotlin led me down the path of duplicating the `Maps` class with the additional code I needed, but this feels a bit odd to me. Is there any other way to do this? The "offending" code is the `Maps.afterInsert` function that instantiates the map without providing an `options` object. Is there a better way around this? TIA!

Mentioning @aSemy as per `rjaros`' advice.

**Comment by aSemy** [comment]
Hi, I'm not sure what you're trying to do. It would help me understand if you can you share some of the code that you've tried?

Before you do though, I can take some guesses....


For the sake of progress you could try disabling type-safety with `asDynamic()` and doing it quickly.

```kotlin
import io.kvision.maps.Maps
import io.kvision.utils.obj

fun createMap() {
  val kvMap: Maps = Maps {
    width = 800.px
    height = 800.px
    margin = 10.px
  }
  
    kvMap.configureLeafletMap {
    val optionsDynamic: dynamic = options.asDynamic()
    optionsDynamic.contextmenuItems = listOf(
      obj {
        text = "Zoom in"
        icon = "images/zoom-in.png"
      },
      "-",
      obj {
        text = "Center map here"
        callback = { e: dynamic ->
          this@configureLeafletMap.panTo(e.latlng)
        }
      },
    )
  }
}
```

Alternatively you could try doing it 'properly' and defining some external interfaces.

My guess is that you don't need to interact with a `ContextMenu` instance, you just need to define them with the `contextmenuItems` options. In which case you just need to define an external interface `ContextMenuOptions`, and then you can do 

```kotlin
    kvMap.configureLeafletMap {
    val optionsDynamic: dynamic = options.asDynamic()
    optionsDynamic.contextmenuItems = listOf(
      obj<ContextMenuOptions> {
        text = "Zoom in"
        icon = "images/zoom-in.png"
      },
      "-",
      obj<ContextMenuOptions> {
        text = "Center map here"
        callback = { e: dynamic ->
          this@configureLeafletMap.panTo(e.latlng)
        }
      },
    )
  }
```

That would probably get you most of the way. 

To go further you could define an external interface for `ContextMenu`. Look at [the code here for defining a 'ContextMenu'](https://github.com/aratcliffe/Leaflet.contextmenu/blob/69478afd4af9adf19ed743847cc9294e396a4d13/src/Map.ContextMenu.js#L5), and use that as a basis for defining a new external interface that extends the existing [`Handler.kt`](https://github.com/rjaros/kvision/blob/90dcbbdfe60e17cd5a1cda7de577bf54b8716549/kvision-modules/kvision-maps/src/main/kotlin/io/kvision/maps/externals/leaflet/core/Handler.kt). You don't need to be exhaustive, you can only focus on the methods you need.

And then instead of using [`mergeOptions`](https://github.com/aratcliffe/Leaflet.contextmenu/blob/69478afd4af9adf19ed743847cc9294e396a4d13/src/Map.ContextMenu.js#L1-L3), just extend `LeafletMapOptions` yourself, add the new properties, and use that to configure the LeafletMap instance.

```kotlin
external interface CustomLeafletMapOptions : LeafletMap.LeafletMapOptions {
 var contextmenuItems : List<Any>
}

...

      val optionsCustom: CustomLeafletMapOptions = options.unsafeCast<CustomLeafletMapOptions>()
      optionsCustom.contextmenuItems = listOf(
        obj<ContextMenuOptions> {
          text = "Zoom in"
          icon = "images/zoom-in.png"
        },
        "-",
        obj {
          text = "Center map here"
          callback = { e: dynamic ->
            this@configureLeafletMap.panTo(e.latlng)
          }
        },
      )
```

It's not going to be very pretty directly though, because it looks like `contextmenuItems` can accept either a `ContextMenuOptions` instance or a String, and Kotlin doesn't have that sort of Type Union support. You could try creating a helper extension function - but personally I'd just stick with `List<Any>`

**Comment by rjaros** [comment]
I've made some tests and it seems options for the context menu have to be set when the map instance is created. Adding options later, within `configureLeafletMap` function is not working for me.
I've changed `Maps` component by adding `val configure: dynamic.() -> Unit` property and passing it to the `L.map(...)` call. After this change I can successfully configure context menu with this code:
```Kotlin
            maps(configure = {
                contextmenu = true
                contextmenuWidth = 140
                contextmenuItems = arrayOf(obj {
                    text = "Show coordinates"
                    callback = { console.log("show") }
                })
            })
```
What do you think?

**Comment by joaofig** [comment]
Thank you very much for both answers and for replying so quickly! Apologies for not being very clear on my rambling question. I think that Robert's response is closer to what I need: a way to add an extension to `LeafletMapOptions` when creating the map object. I did it with my version of the code, but I needed a complete rewrite of the `Maps` class to hold the configuration object and then submit it when creating on the `afterInsert` call. Something like:
```
    var options = obj<LeafletMapOptions> { } 
.
.
.
    override fun afterInsert(node: VNode) {
        val thisElement: HTMLElement = requireNotNull(this.getElement() as? HTMLElement) {
            "$this - Unable to get HTMLElement"
        }

        _leafletMap = LeafletMap(thisElement, options)
        _leafletMap!!.leafletMapConfigurer()
    }
```
This allows me to define what to put in the options object before creating the map ad adding it to the document.
