### ISSUE TITLE
Navigo routing hooks - Done function should accept boolean parameter

### ISSUE THREAD

**Issue by JoonasC** [rjaros/kvision#405]
According to the Navigo documentation the `done` function that is present in certain hooks should be able to accept an argument: 

> The before hook receives two arguments. The first one is a function that needs to be called with either no arguments or false. The no-argument version means "move forward". false stops the resolving and your handler will not be called

Despite this, the KVision definition for the `RouteHooks` interface only has the no-argument version of the function, which makes it impossible to stop the resolution of a route from a hook.

**Comment by rjaros** [comment]
Unfortunately Kotlin doesn't support default parameters in function types and it can't be simply implemented with external mappings. I see three possibilities:

1. Change the `done` function type to always require `Boolean` argument. Unfortunately it would break existing code and require calling `done(true)` instead of `done()` everywhere.
2. Change the `done` function type to `dynamic`. It won't break existing code but we loose strict function typing.
3. Leave it as it is and use a workaround for this case (you can use simple `done.asDynamic()(false)`)

What do you think?

**Comment by JoonasC** [comment]
I think something like this could be done:
```kotlin
class HookTerminationUtil(private val done: dynamic) {
    fun continueResolution() {
        done()
    }

    fun stopResolution() {
        done(false)
    }
}

typealias Handler = HookTerminationUtil.(Match) -> Unit
```

Then in the code that runs when the hook is triggered you could do something like this:
```kotlin
val hookTerminationUtil = HookTerminationUtil(done)
hookTerminationUtil.handler(match)
```

This would allow you to use hooks like this:
```kotlin
routing.hooks(obj<RouteHooks> {
    before = { match ->
        val condition: Boolean = hookLogic(match)

        if (condition)
            continueResolution()
        else
            stopResolution()
    }
})
```

**Comment by rjaros** [comment]
I've came up with this:
```Kotlin
@Suppress("IMPLEMENTING_FUNCTION_INTERFACE")
abstract class DoneFunction : () -> Unit {
    operator fun invoke(continueResolution: Boolean) {
        this.asDynamic()(continueResolution)
    }
}
```
It works perfectly with IR backend (you can simply call `done()` or `done(false)`), but unfortunately `done(false)` do not work with  the legacy compiler (though `done.asDynamic()(false)` works). Still it seems the best solution for me and I'll add this to the next release.
