### ISSUE TITLE
XSS protection documentation

### ISSUE THREAD

**Issue by JoonasC** [rjaros/kvision#414]
Currently, the kvision guide doesn't mention anything at all about XSS. Is this because kvision is immune to XSS? It would be nice to have some documentation on this to know what are dangerous things you shouldn't do, if there are any.

**Comment by rjaros** [comment]
By default KVision is safe from XSS, as long as you don't use `rich = true` attribute, which is unsafe by design - https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/basic-components#rich-text. Rich text is also automatically used by handlebar.js templates - https://kvision.gitbook.io/kvision-guide/3.-optional-ui-functionality-via-modules/handlebars.js-templates.

I'll try to add a chapter to the guide soon.
