### ISSUE TITLE
[BUG] Inheritance based components - Overriden afterInsert function is not called upon DOM changes unless addAfterInsertHook has been called

### ISSUE THREAD

**Issue by JoonasC** [rjaros/kvision#428]
In inheritance based components the overriden `afterInsert` function is not called upon DOM changes unless the `addAfterInsertHook` function has been called.

Take the following example:
```kotlin
var customComponent = null
val div = div {
    customComponent = CustomComponent()
    add(customComponent)
}
button("Change DOM").onClick {
    val newCustomComponent = CustomComponent()
    div.remove(customComponent)
    div.add(newCustomComponent)
    customComponent = newCustomComponent
}
```
The `afterInsert` function of the `CustomComponent` inheritance based component will be called only upon page load, but not when clicking the button.

For some reason the `addAfterInsertHook` function needs to be called for this to work:
```kotlin
var customComponent = null
val div = div {
    customComponent = CustomComponent()
    add(customComponent)
}
button("Change DOM").onClick {
    val newCustomComponent = CustomComponent()
    newCustomComponent.addAfterInsertHook { println("After insert") }
    div.remove(customComponent)
    div.add(newCustomComponent)
    customComponent = newCustomComponent
}
```

**Comment by rjaros** [comment]
It's not really a bug. It's a feature ;-)
The `afterInsert` function or hook is generally called, when new DOM element is created and inserted into the DOM tree. But snabbdom (our virtual DOM library) is optimizing this process. When you remove a component (which is for instance a DIV element) and at the same time add a different component (which is also a DIV) snabbdom doesn't have to create and insert new DOM element - it will just reuse the old DIV element. And no hook will be called. It's good because it's fast. At the same time it can be a problem, because sometimes we need a hook to always give us access to the specific HTML element (e.g. to add some low level handlers). Snabbdom has an option to mark virtual nodes with unique keys. In KVision this marking is easily enabled with `useSnabbdomDistinctKey()` protected method from the `Widget` class. So if you have problems with component lifecycle - just call this method in your component `init` block. It should work. And `addAfterInsertHook` function calls this method internally - that's why it is working fine for you.

**Comment by JoonasC** [comment]
Ok, might be good to add a note about this in the documentation.

**Comment by rjaros** [comment]
Updated guide:
https://kvision.gitbook.io/kvision-guide/2.-frontend-development-guide/dom-bindings#lifecycle-hooks
