### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#500]
How do I get rid of this error message on tablutor table which only shows on my smaller laptop screen but not on my larger second screen

```
Uncaught runtime errors:
ERROR
ResizeObserver loop completed with undelivered notifications.
    at handleError (webpack-internal:///../../node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///../../node_modules/webpack-dev-server/client/overlay.js:271:7)
```

**Comment by rjaros** [comment]
If you want to get rid of overlay error message from webpack, you can add this to your `webpack.config.d/webpack.js`:
```
if (config.devServer) {
    config.devServer.client = {
        overlay: false
    };
}
```
The root cause of the message is probably some bug in the tabulator library (there are some issues opened regarding ResizeObserver), but I'm not sure we can do anything about this in KVision.

**Comment by chavu** [comment]
Thank you. This worked.
