### ISSUE TITLE
Problem with KFiles

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#55]
I'm using the KFile form control but I am not able to get any content from the file, it just returns `null`, this is also the case if you try to upload a file to the Showcase form tab and then click show data, it just reveals `null` for content.
Any ideas on why this might be?

Specifically, I am trying to get either a Base64 or Binary representation of the file

**Comment by rjaros** [comment]
KFile is a special object created to represent uploaded file, and it needs special handling because file upload is an asynchronous operation. It returns null content without it, and it's not a bug. 
I've described it briefly in the guide: 
https://kvision.gitbook.io/kvision-guide/part-2-advanced-features/form-controls-guide#client-side-file-handling 

You need to use one of suspending extension functions (of course run from any coroutine builder) defined in `kvision-upload` module in `utils` package: `Form<K>.getDataWithFileContent()` or `FormPanel<K>.getDataWithFileContent()`.

**Comment by robert-cronin** [comment]
Thank you, I should have read a bit further, that is working perfectly now 👍

**Comment by robert-cronin** [comment]
On the same note, how would I get a KFile from base64 content? I can do uploading file, but I'm struggling with opening the file in another window once I download the base64 string

**Comment by rjaros** [comment]
Why do you need a `KFile`? It's just a data class for holding file name, size and content.

**Comment by robert-cronin** [comment]
Well like I said in my comment, I would like to find a way to convert base64 into a file and open it.
I'm not sure what KVision uses to convert binary data into base64 but I've just discovered `window.btoa()` so I think my issue is solved.

**Comment by rjaros** [comment]
KVision uses `FileReader.readAsDataURL()`.

**Comment by robert-cronin** [comment]
I didn't have much success with `FileReader`, perhaps it's worth checking out again, I didn't know about that method
