### ISSUE TITLE
Setting width equal to 100 percent doesn't work

### ISSUE THREAD

**Issue by robert-cronin** [rjaros/kvision#82]
It seems the HPanel element is created in an enclosing div that is not accessible to the user in KVision. If you set the width of a HPanel to 100 percent, the HPanel div will try to fit in the enclosing div and not the actual parent element, resulting in no change in width.

**Comment by robert-cronin** [comment]
this issue appears to be the same for every component.

**Comment by rjaros** [comment]
`HPanel` is using flexbox css layout. You can make enclosing element stretch by using `alignItems = FlexAlignItems.STRETCH`.

**Comment by robert-cronin** [comment]
Flex Stretch doesn't seem to work either, I have decided to go with a ResponsiveGridPanel instead of hPanel, it seems to do the trick

**Comment by rjaros** [comment]
Good to know, but if you could post your problematic HPanel code, we could find a solution or fix some bug.

**Comment by robert-cronin** [comment]
Sorry it has taken so long, but I've come up with an example code using `hPanel`:
```
SimplePanel {
                background = Background(Col.SKYBLUE)
                hPanel {
                    background = Background(Col.RED)
                    alignItems = FlexAlignItems.STRETCH
                    Span("Span 1").also { add(it); background = Background(Col.GREEN) }
                    Span("Span 2").also { add(it); background = Background(Col.YELLOW) }
                    Span("Span 3").also { add(it); background = Background(Col.ORANGE) }
                }
            }
```
This is the result:
![image](https://user-images.githubusercontent.com/8540764/62746226-253fda80-ba81-11e9-877a-a0d599b2adbb.png)
The other thing I noticed is that the background colour of the whole element seems to be set to the last span as well as the items not being stretched out

**Comment by robert-cronin** [comment]
Also `FlexAlignItems.STRETCH` seems to have no effect, when I remove it nothing changed.

**Comment by rjaros** [comment]
I'm still not sure about the 100 percent problem you mentioned in the first comment. It seems to work fine for me. As for your example - you have made a simple error. Inside `also` you should use `it.background` because `background` references hPanel's property (it is just set four times to different values and the last one is being used).

Also, in flexbox "alignItems" applies to orthogonal direction - so inside hPanel align property applies to top-bottom alignment. And you just want to "justify" elements in left-right direction, e.g:
```
        hPanel(justify = FlexJustify.SPACEBETWEEN) {
            background = Background(Col.RED)
            Span("Span 1").also { add(it); it.background = Background(Col.GREEN) }
            Span("Span 2").also { add(it); it.background = Background(Col.YELLOW) }
            Span("Span 3").also { add(it); it.background = Background(Col.ORANGE) }
        }
```
Of course you can use other values like FlexJustify.CENTER, FlexJustify.SPACEAROUND or others.

**Comment by robert-cronin** [comment]
This is solved for me 👍
